export const properties = [
  {
    name: "Palm Harbor",
    address: "2699 Green Valley, Highland",
    image: "https://bit.ly/3yJ4ulJ",
    city: "Miami",
    price: "2095",
    type: "apartment",
    moveIn: "10/30/2022",
    details: {
      rooms: "3",
      bathrooms: "2",
      area: "5x7",
    },
  },
  {
    name: "Beverly Springfield",
    address: "2821 Lake Sevilla, Palm Harbor",
    image: "https://bit.ly/3TnmIkH",
    city: "Dallas",
    price: "2700",
    type: "apartment",
    moveIn: "11/15/2022",
    details: {
      rooms: "4",
      bathrooms: "2",
      area: "6x7.5",
    },
  },
  {
    name: "Faulkner Ave",
    address: "909 Woodland st.",
    image: "https://bit.ly/3CBcJBJ",
    city: "Lansing",
    price: "4550",
    type: "house",
    moveIn: "11/10/2022",
    details: {
      rooms: "4",
      bathrooms: "3",
      area: "8x10",
    },
  },
  {
    name: "Test 1",
    address: "xyz street",
    image: "https://bit.ly/3S5c0ym",
    city: "New York",
    price: "5600",
    type: "villa",
    moveIn: "10/20/2022",
    details: {
      rooms: "5",
      bathrooms: "3",
      area: "12x10",
    },
  },
  {
    name: "Test 2",
    address: "xyz street",
    image: "https://bit.ly/3CZI6ae",
    city: "Scranton",
    price: "2200",
    type: "apartment",
    moveIn: "10/20/2022",
    details: {
      rooms: "2",
      bathrooms: "1",
      area: "5x6",
    },
  },
  {
    name: "Test 3",
    address: "xyz street",
    image: "https://bit.ly/3MCk1tC",
    city: "Austin",
    price: "3600",
    type: "house",
    moveIn: "11/20/2022",
    details: {
      rooms: "3",
      bathrooms: "2",
      area: "8x10",
    },
  },
  {
    name: "Test 4",
    address: "abc street",
    image: "https://bit.ly/3CycwPv",
    city: "Seattle",
    price: "9900",
    type: "studio_apartment",
    moveIn: "01/01/2023",
    details: {
      rooms: "3",
      bathrooms: "2",
      area: "15x20",
    },
  },
  {
    name: "Test 5",
    address: "abc street",
    image: "https://bit.ly/3RXE3Qc",
    city: "Denver",
    price: "4000",
    type: "villa",
    moveIn: "10/25/2022",
    details: {
      rooms: "2",
      bathrooms: "2",
      area: "10x12",
    },
  },
  {
    name: "Test 6",
    address: "pqr street",
    image: "https://bit.ly/3CYSejv",
    city: "Chicago",
    price: "800",
    type: "apartment",
    moveIn: "11/20/2022",
    details: {
      rooms: "1",
      bathrooms: "1",
      area: "4x5",
    },
  },
  {
    name: "Test 7",
    address: "lmn street",
    image: "https://bit.ly/3yHMF6H",
    city: "Chicago",
    price: "900",
    type: "apartment",
    moveIn: "10/30/2022",
    details: {
      rooms: "1",
      bathrooms: "1",
      area: "4x5",
    },
  },
  {
    name: "Test 8",
    address: "abc street",
    image: "https://bit.ly/3rZglbO",
    city: "New York",
    price: "2750",
    type: "apartment",
    moveIn: "1/12/2022",
    details: {
      rooms: "2",
      bathrooms: "1",
      area: "8x10",
    },
  },
  {
    name: "Test 9",
    address: "abc street",
    image: "https://bit.ly/3CybrqV",
    city: "Austin",
    price: "7000",
    type: "villa",
    moveIn: "11/30/2022",
    details: {
      rooms: "4",
      bathrooms: "2",
      area: "10x15",
    },
  },
];
